# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
