# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20151217_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='zip',
            new_name='zip_file',
        ),
    ]
