# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_dataset_uuid'),
        ('submissions', '0006_auto_20151218_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='dataset',
        ),
        migrations.AddField(
            model_name='submission',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='datasets.Dataset'),
        ),
    ]
