# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20151219_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='datasets.Dataset'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
