# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20151219_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='duration',
        ),
    ]
