# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_auto_20151219_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
