# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_remove_submission_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
